# Generated by Django 4.2.7 on 2023-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailing_owner_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(related_name='client', to='mailings.client', verbose_name='клиент'),
        ),
    ]
